on: [push]
name: Security audit
jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: security-audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

